### ISSUE TITLE
Unhandled rejection TypeError: (intermediate value).cancellable is not a function

### ISSUE THREAD

**Issue by aradnom** [kisi-inc/client-js#17]
```
Unhandled rejection TypeError: (intermediate value).cancellable is not a function
    at Request.promise (/Users/me/htdocs/bau-api.derp/node_modules/superagent-bluebird-promise/index.js:53:6)
    at Request.then (/Users/me/htdocs/bau-api.derp/node_modules/superagent-bluebird-promise/index.js:72:22)
    at /Users/me/htdocs/bau-api.derp/node_modules/kisi-client/lib/index.js:92:6
    at tryCatcher (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/promise.js:69:37)
    at Rest._dispatch (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/lib/index.js:76:10)
    at Rest.post (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/lib/index.js:59:15)
    at /Users/me/htdocs/bau-api.derp/node_modules/kisi-client/lib/index.js:30:11
    at tryCatcher (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/node_modules/bluebird/js/main/promise.js:69:37)
    at Rest.authenticate (/Users/me/htdocs/bau-api.derp/node_modules/kisi-client/lib/index.js:29:10)
    at /Users/me/htdocs/bau-api.derp/config/bootstrap.js:35:10
    at tryCatcher (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._fulfillPromises (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/promise.js:651:14)
    at Promise._settlePromises (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/promise.js:677:18)
    at Async._drainQueue (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/me/htdocs/bau-api.derp/node_modules/bluebird/js/release/async.js:135:10)
```
While trying to authenticate.  One of your intermediate steps in the request promise chain isn't returning a promise.

**Comment by ce07c3** [comment]
Closed as we update to #18.
